apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
        - name: metadata
          image: kuisskui/metadata:v1
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: metadata
spec:
  selector:
    app: metadata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
